### ISSUE TITLE
Unable to login once refresh token expires

### ISSUE THREAD

**Issue by MikeEdgar** [streamshub/console#426]
It seems as though once the refresh token has expired or is no longer valid, it is not possible to login without clearing the site's cookies.

Otherwise, the error page is displayed
![image](https://github.com/eyefloaters/console/assets/20868526/f66f2b96-31aa-4bc0-ab97-605d232eb89c)

**Comment by riccardo-forina** [comment]
Uhm I cannot reproduce this. I just tried to log in both on the demo cluster and locally - both with sessions that are surely expired now - and in both cases, I got redirected to the login page.

**Comment by MikeEdgar** [comment]
Maybe this only happens locally? Maybe it's not worth much effort if that is the case. I'm also using Firefox, which may be related. I'll try with another browser today.

**Comment by MikeEdgar** [comment]
Closing because this was related to the Keycloak integration which was removed in an earlier version.
