### ISSUE TITLE
Create github actions to test playwright tests

### ISSUE THREAD

**Issue by suyash-naithani** [streamshub/console#505]
We have page level testing done with playwright. Our next step should be to run these tests for every PR so that we can identify any bugs or breaking changes on the deployed demo before merging them into our codebase.

- Create github action to run the playwright test for ever PR raised against the main branch.
-  Run the UI server against the cluster api deployed on the demo inside the github action to test for any breaking changes the PR may cause in the demo environment. This way we can test the functioning of the demo before releasing any updates to the demo env.

**Comment by MikeEdgar** [comment]
Done in #607
